IF OBJECT_ID('dbo.users', 'U') IS NULL CREATE TABLE users (
    id_user UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
    nome VARCHAR(256) NOT NULL,
    age INT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at AS CURRENT_TIMESTAMP
);